Authorization Endpoint の作成
saitamau-maximum/auth pull request #33
Opened 2024-11-07 08:50 UTC by a01sa01to

close #27 

コミットメッセージはどうせ Squash するので適当です　許せ
一応ローカル手動テストは通ってそう

デザインは任せた

2024-11-07 08:57 UTC, sor4chi commented
> コミットメッセージはどうせ Squash するので適当です　許せ
無理

2024-11-07 09:00 UTC, a01sa01to commented
はい

2024-11-07 09:04 UTC, sor4chi requested changes

2024-11-07 09:04 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +    }
フロントにエラー理由載せたいってこと？
cookieじゃダメなの？

2024-11-07 09:04 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +    }
識別子をparamに載せるのはいいんだけど文章を乗せたくはない

2024-11-07 09:04 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +  validator('query', async (query, c: Context<HonoEnv>) => {
やり方悪いだけな気がする
https://hono.dev/examples/validator-error-handling#error-handling-in-validator
第三引数でエラー理由を取ってカスタムエラーで返せす

2024-11-07 09:04 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +    )[0]
index zero access (undefined included)の時は`.at(0)`の方が良き

2024-11-07 09:04 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +    }
変数の上書きやめて、フラグでどうにかして欲しいよ

2024-11-07 09:04 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +        return c.text('Bad Request: too many state')
status code正常じゃないこれ？

2024-11-07 09:04 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +      const scopeRegex =
どうでもいいけどregexのオブジェクト毎回生成すると重いよ

2024-11-07 09:09 UTC, a01sa01to commented on webapp/api/oauth/authorize.ts
> +    }
？

> 識別子をparamに載せるのはいいんだけど文章を乗せたくはない

これどこ指してる？

`error_uri` の想定はエラーに対するドキュメント的なやつで詰まったときにメンバーが見れるといいのかなーっていう想定

2024-11-07 09:10 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +        return c.text('Bad Request: too many state')
というかこれ条件分岐汚いな

2024-11-07 09:12 UTC, a01sa01to commented on webapp/api/oauth/authorize.ts
> +  validator('query', async (query, c: Context<HonoEnv>) => {
第 3 引数の存在は知ってるけど、エラー理由 => response msg の変換めんどくさくないか？

2024-11-07 09:12 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +  validator('query', async (query, c: Context<HonoEnv>) => {
ベタガキするよりはいいと思う
めんどくささよりも綺麗さ優先したい
綺麗になるならいいけど

2024-11-07 10:01 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +    }
これsearch paramにerror載せるのはOAuthの仕様なの？

サーバーからクライアントのHTMLにメッセージ送りたい時基本的にはcookieを使うと思うので
https://github.com/saitamau-maximum/simple-hono-session-auth/blob/8ffbee5c0a85d22c2c25215977f3b61174ae28d2/index.js#L122

2024-11-07 10:07 UTC, a01sa01to commented on webapp/api/oauth/authorize.ts
> +    }
これは仕様です

https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1
> If the resource owner denies the access request or if the request fails for reasons other than a missing or invalid redirection URI, the authorization server informs the client by adding the following parameters to the query component of the redirection URI using the "application/x-www-form-urlencoded" format

2024-11-07 10:10 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +    }
把握、意外だった

2024-11-07 10:53 UTC, sor4chi commented
なんかよくなってそう

2024-11-08 04:06 UTC, sor4chi reviewed
あとちょい

validateのとこ、前よりは綺麗になったと思うんだけど、スコープブロックで分けるとか関数で切り出すとかしてなるべくぱっと見で処理がわかるような書き方だといいなと思った

2024-11-08 04:06 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +        })
下の方でfindManyするなら上の方もfindFirstとかでクエリした方がいいかも？

2024-11-08 04:06 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +    }[]
これ型大域に加工

2024-11-08 04:11 UTC, a01sa01to commented on webapp/api/index.ts
> +app.route('/oauth/authorize', oauthAuthorizeRoute)
#28 #29

2024-11-08 04:13 UTC, a01sa01to commented on webapp/api/oauth/authorize.ts
> +        })
JOIN するときに query だとうまくいかなかったので...
schema で relation 作るとできるらしいけど、まあ refactor として別 PR で対応すればいいかになってた

2024-11-08 04:16 UTC, sor4chi commented on webapp/api/index.ts
> +app.route('/oauth/authorize', oauthAuthorizeRoute)
??

2024-11-08 04:19 UTC, a01sa01to commented on webapp/api/index.ts
> +app.route('/oauth/authorize', oauthAuthorizeRoute)
？？？
access token, callback も oauth 配下だよ

2024-11-08 05:14 UTC, sor4chi commented on webapp/api/index.ts
> +app.route('/oauth/authorize', oauthAuthorizeRoute)
そういうことか、L30-33にoauthっていうパスが入ってなかったから気になった

2024-11-08 05:16 UTC, a01sa01to commented on webapp/api/index.ts
> +app.route('/oauth/authorize', oauthAuthorizeRoute)
あー、 L30-33 は現行の Auth 向けのパスだからね　そのうち消すよ

2024-11-08 05:21 UTC, sor4chi commented on webapp/api/index.ts
> +app.route('/oauth/authorize', oauthAuthorizeRoute)
そうだったのよ、実はこれ4行セレクトしてるんだよね
ごめん無視してもらっていいわ

2024-11-08 05:21 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +        })
OK-

2024-11-08 05:21 UTC, sor4chi commented on webapp/api/oauth/authorize.ts
> +    }[]
その時camelにした方がいいかも？でもこれdbの値か

2024-11-08 05:28 UTC, sor4chi approved these changes
あざます！

2024-11-08 08:39 UTC, merged